Repository CoolCoders23/AdsTrees, pull requests merged in 2024-01, with the labels that each got.

#39 "Implement Offline Access and Installability for AdsTrees PWA"
  client/index.html
  client/package.json
  client/public/Favicon32.ico
  client/public/apple-touch-icon.png
  client/public/favicon-32x32.ico
  client/public/favicon.ico
  client/public/favicon.svg
  client/public/pwa-192x192.png
  client/public/pwa-512x512.png
  client/public/pwa-64x64.png
  client/public/robots.txt
  client/src/App.css
  client/src/assets/image/AdsTrees_Logo_128.svg
  client/src/assets/image/AdsTrees_Logo_48.svg
  client/src/assets/image/Logo/Logo128x128.png
  client/src/assets/image/Logo/Logo256x256.png
  client/src/assets/image/Logo/Logo512x512.png
  client/src/assets/image/Logo/Logo64x64.png
  client/src/assets/image/Logo/LogoMain.png
  client/src/assets/image/LogoMain/AdsTrees_Logo_1024.svg
  client/src/assets/image/LogoMain/AdsTrees_Logo_256.svg
  client/src/assets/image/LogoMain/AdsTrees_Logo_512.svg
  client/src/assets/image/LogoMain/AdsTrees_Logo_64.svg
  client/src/assets/image/LogoMain/Bay Leaf.png
  client/src/assets/image/Team/ehsan.jpeg
  client/src/assets/image/Team/jide.jpg
  client/src/assets/image/Team/marko.png
  client/src/assets/image/Team/yega.jpg
  client/src/assets/image/spinner.gif
  client/src/components/Header/index.jsx
  client/src/main.jsx
  client/vite.config.js
Labels: documentation, enhancement

#42 Integrated styling into contact, signup, and login page.
  client/src/App.css
  client/src/pages/AdsTreesContactUs/AdsTreesContactUs.css
  client/src/pages/AdsTreesSignIn/AdsTreesSignIn.css
  client/src/pages/AdsTreesSignUp/AdsTreesSignUp.css
  client/src/pages/Contact.jsx
  client/src/pages/Login.jsx
  client/src/pages/Signup.jsx
Labels: enhancement

#45 Fixed console errors and signup page
  client/src/pages/Contact.jsx
  client/src/pages/Signup.jsx
Labels: enhancement

#46 React components polish
  client/src/App.css
  client/src/App.jsx
  client/src/components/AdsTreeFooter/index.jsx
  client/src/components/Header/Header.css
  client/src/images/Ehsan.png
  client/src/images/Jide.png
  client/src/images/Marko.png
  client/src/images/Yega.png
  client/src/main.jsx
  client/src/pages/About/About.css
  client/src/pages/About/About.jsx
  client/src/pages/AdsTreesSignUp/AdsTreesSignUp.css
  client/src/pages/Contact.jsx
  client/src/pages/Login.jsx
  client/src/pages/Signup.jsx
  client/src/utils/theme.js
  package.json
Labels: enhancement

#49 This Creates the dashboard page
  client/package.json
  client/src/components/DonationHistory/index.jsx
  client/src/main.jsx
  client/src/pages/AddsTreesDashboard/StatsComponent/StatsComponent.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/Dashboard/AddsTreesDashboard.css
  client/src/pages/Dashboard/BonusCard/BonusCard.css
  client/src/pages/Dashboard/BonusCard/BonusCard.jsx
  client/src/pages/Dashboard/CkArrowRight/CkArrowRight.css
  client/src/pages/Dashboard/CkArrowRight/CkArrowRight.jsx
  client/src/pages/Dashboard/ProgressSizeXsColorSchemeGreen/ProgressSizeXsColorSchemeGreen.css
  client/src/pages/Dashboard/ProgressSizeXsColorSchemeGreen/ProgressSizeXsColorSchemeGreen.jsx
  client/src/pages/Dashboard/ProgressStripe/ProgressStripe.css
  client/src/pages/Dashboard/ProgressStripe/ProgressStripe.jsx
  client/src/pages/Dashboard/StatsComponent/StatsComponent.css
  client/src/pages/Dashboard/StatsComponent/StatsComponent.jsx
  client/src/pages/Dashboard/StatsComponentHeader/StatsComponentHeader.css
  client/src/pages/Dashboard/StatsComponentHeader/StatsComponentHeader.jsx
  client/src/pages/Dashboard/StatsFigureCard/StatsFigureCard.css
  client/src/pages/Dashboard/StatsFigureCard/StatsFigureCard.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Profile/AdsTreesProfile.css
  client/src/pages/Profile/CheckboxGroup/CheckboxGroup.css
  client/src/pages/Profile/CheckboxGroup/CheckboxGroup.jsx
  client/src/pages/Profile/index.jsx
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/Ad.js
  server/models/Donation.js
  server/models/Purchase.js
  server/models/User.js
  server/models/Youtube.js
  server/models/index.js
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/adSeeds.js
  server/seeders/seed.js
  server/seeders/userSeeds.js
  server/seeders/youtubeSeeds.js
  server/server.js
Labels: enhancement

#47 Create README.md
  README.md
Labels: documentation

#67 Fix performance issues and add new features
  client/src/App.css
  client/src/App.jsx
  client/src/assets/workFlow.md
  client/src/components/Cart/cart.css
  client/src/components/Cart/index.jsx
  client/src/components/CartItem/index.jsx
  client/src/components/CheckoutForm/CheckoutForm.css
  client/src/components/CheckoutForm/index.jsx
  client/src/components/DonationHistory/index.jsx
  client/src/components/DonationSummary/DonationSummary.css
  client/src/components/DonationSummary/index.jsx
  client/src/components/Header/CartIcon/CartIcon.css
  client/src/components/Header/CartIcon/CartIcon.jsx
  client/src/components/Header/index.jsx
  client/src/components/PricingCard/PricingCard.jsx
  client/src/main.jsx
  client/src/pages/About/index.jsx
  client/src/pages/Checkout/Checkout.css
  client/src/pages/Checkout/index.jsx
  client/src/pages/Dashboard/StatsComponent/StatsComponent.jsx
  client/src/pages/Dashboard/index.jsx
  client/src/pages/Profile/AdsTreesProfile.css
  client/src/pages/Success/index.jsx
  client/src/utils/mutations.js
  client/src/utils/payment-logic/StateProvider.jsx
  client/src/utils/payment-logic/actions.js
  client/src/utils/payment-logic/idbHelper.js
  client/src/utils/payment-logic/reducers.js
  client/src/utils/queries.js
  client/vite.config.js
  server/config/connection.js
  server/config/seeds.js
  server/models/Purchase.js
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/adSeeds.js
  server/seeders/purchaseSeeds.js
  server/seeders/userSeeds.js
Labels: enhancement

#68 Add video progress bar to Dashboard page
  client/src/pages/Dashboard/ProgressSizeXsColorSchemeGreen/ProgressSizeXsColorSchemeGreen.css
  client/src/pages/Dashboard/ProgressSizeXsColorSchemeGreen/ProgressSizeXsColorSchemeGreen.jsx
  client/src/pages/Dashboard/ProgressStripe/ProgressStripe.jsx
  client/src/pages/Dashboard/index.jsx
Labels: enhancement

#69 Refactor code and update styles
  client/src/App.css
  client/src/App.jsx
  client/src/components/CheckoutForm/CheckoutForm.css
  client/src/components/CheckoutForm/index.jsx
  client/src/components/DonationHistory/index.jsx
  client/src/components/DonationSummary/DonationSummary.css
  client/src/components/Footer/Footer.css
  client/src/components/Footer/index.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/MainNavigationButtonTargetDashboardStatusActive/MainNavigationButtonTargetDashboardStatusActive.css
  client/src/components/Header/MainNavigationButtonTargetDashboardStatusActive/MainNavigationButtonTargetDashboardStatusActive.jsx
  client/src/components/Header/MainNavigationButtonTargetProfileStatusActive/MainNavigationButtonTargetProfileStatusActive.css
  client/src/components/Header/MainNavigationButtonTargetProfileStatusActive/MainNavigationButtonTargetProfileStatusActive.jsx
  client/src/components/Header/TargetLogoutStatusActive/TargetLogoutStatusActive.css
  client/src/components/Header/TargetLogoutStatusActive/TargetLogoutStatusActive.jsx
  client/src/components/Header/index.jsx
  client/src/components/PricingCard/PricingCard.css
  client/src/components/PricingCard/PricingCard.jsx
  client/src/main.jsx
  client/src/pages/About/About.css
  client/src/pages/About/index.jsx
  client/src/pages/Checkout/Checkout.css
  client/src/pages/Checkout/index.jsx
  client/src/pages/Contact/AdsTreesContactUs.css
  client/src/pages/Contact/index.jsx
  client/src/pages/Dashboard/AddsTreesDashboard.css
  client/src/pages/Dashboard/BonusCard/BonusCard.css
  client/src/pages/Dashboard/CkArrowRight/CkArrowRight.jsx
  client/src/pages/Dashboard/ProgressSizeXsColorSchemeGreen/ProgressSizeXsColorSchemeGreen.css
  client/src/pages/Dashboard/StatsComponent/StatsComponent.css
  client/src/pages/Dashboard/StatsComponentHeader/StatsComponentHeader.css
  client/src/pages/Dashboard/StatsFigureCard/StatsFigureCard.css
  client/src/pages/Dashboard/index.jsx
  client/src/pages/Donations/index.css
  client/src/pages/Login/AdsTreesSignIn.css
  client/src/pages/Login/index.jsx
  client/src/pages/Profile/AdsTreesProfile.css
  client/src/pages/Profile/index.jsx
  client/src/pages/Signup/AdsTreesSignUp.css
  client/src/pages/Signup/index.jsx
  client/src/pages/Success/index.css
  client/src/pages/Success/index.jsx
  client/src/theme/components/button.js
  client/src/theme/components/input.js
  client/src/theme/foundations/borders.js
  client/src/theme/foundations/colors.js
  client/src/theme/foundations/fonts.js
  client/src/theme/index.js
  client/src/theme/styles.js
  client/src/utils/theme.js
Labels: enhancement
